In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math

## 1. Viết hàm tính các chuẩn p = 1, 2, inf cho 50 dòng đầu tiên của array.

In [11]:
df = pd.read_csv('/content/ionosphere.data', header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307,g
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712,g
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577,g
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243,g
350,1,0,0.84710,0.13533,0.73638,-0.06151,0.87873,0.08260,0.88928,-0.09139,...,-0.15114,0.81147,-0.04822,0.78207,-0.00703,0.75747,-0.06678,0.85764,-0.06151,g

In [12]:
df.pop(df.columns[-1])
df

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,0.56811,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.20332,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,0.57528,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,1.00000,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,0.03286,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,0.95378,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.94520,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.93988,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,0.91050,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243
350,1,0,0.84710,0.13533,0.73638,-0.06151,0.87873,0.08260,0.88928,-0.09139,...,0.86467,-0.15114,0.81147,-0.04822,0.78207,-0.00703,0.75747,-0.06678,0.85764,-0.06151

In [13]:
# array
array = df.values
print(array)

point1 = array[0, :]
point2 = array[1, :]
point3 = array[2, :]
# p=1
dist01_2 = np.linalg.norm(point1 - point2, 1)
dist01_3 = np.linalg.norm(point1 - point3, 1)
# p=2
dist1_2 = np.linalg.norm(point1 - point2)
dist1_3 = np.linalg.norm(point1 - point3)
# p=inf
dist11_2 = np.linalg.norm(point1 - point2, np.inf)
dist11_3 = np.linalg.norm(point1 - point3, np.inf)
# print results
print(dist1_2)
print(dist1_3)
print(dist01_2)
print(dist01_3)
print(dist11_2)
print(dist11_3)

[[ 1.       0.       0.99539 ... -0.54487  0.18641 -0.453  ]
 [ 1.       0.       1.      ... -0.06288 -0.13738 -0.02447]
 [ 1.       0.       1.      ... -0.2418   0.56045 -0.38238]
 ...
 [ 1.       0.       0.94701 ...  0.00442  0.92697 -0.00577]
 [ 1.       0.       0.90608 ... -0.03757  0.87403 -0.16243]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]]
2.7763589251571923
1.1697276018372824
13.080950000000001
5.359709999999999
1.12221
0.45772

In [14]:
def compute_distance_matrices(array, num_rows=50):
    # Lấy 50 dòng đầu tiên
    data = array[:num_rows, :]
    n = data.shape[0]

    # Tạo ma trận khoảng cách
    dist_matrix_p1 = np.zeros((n, n))  # p = 1 (Manhattan)
    dist_matrix_p2 = np.zeros((n, n))  # p = 2 (Euclidean)
    dist_matrix_pinf = np.zeros((n, n))  # p = inf (Chebyshev)

    # Tính khoảng cách giữa tất cả các cặp điểm
    for i in range(n):
        for j in range(i + 1, n):
            # Tạo 2 điểm
            point1 = data[i, :]
            point2 = data[j, :]

            # p=1
            dist_p1 = np.linalg.norm(point1 - point2, 1)
            dist_matrix_p1[i, j] = dist_p1
            dist_matrix_p1[j, i] = dist_p1

            # p=2
            dist_p2 = np.linalg.norm(point1 - point2, 2)
            dist_matrix_p2[i, j] = dist_p2
            dist_matrix_p2[j, i] = dist_p2

            # p=inf
            dist_pinf = np.linalg.norm(point1 - point2, np.inf)
            dist_matrix_pinf[i, j] = dist_pinf
            dist_matrix_pinf[j, i] = dist_pinf

    # Tạo nhãn ma trận
    labels = [f"p{i+1}" for i in range(n)]

    # Print results
    print("\nManhattan, p=1:")
    df_dist_p1 = pd.DataFrame(dist_matrix_p1, index=labels, columns=labels)
    print(df_dist_p1.round(4))

    print("\nEuclidean, p=2:")
    df_dist_p2 = pd.DataFrame(dist_matrix_p2, index=labels, columns=labels)
    print(df_dist_p2.round(4))

    print("\nChebyshev, p=inf:")
    df_dist_pinf = pd.DataFrame(dist_matrix_pinf, index=labels, columns=labels)
    print(df_dist_pinf.round(4))

compute_distance_matrices(array, num_rows=50)

Manhattan, p=1:
          p1       p2       p3       p4       p5       p6       p7       p8  \
p1    0.0000  13.0810   5.3597  21.0573   6.2139  15.1663   7.5770  22.2870
p2   13.0810   0.0000  15.8004  20.7696  11.5262  12.5880  12.2811  22.6390
p3    5.3597  15.8004   0.0000  20.3048   8.5042  14.2484  11.5754  21.1658
p4   21.0573  20.7696  20.3048   0.0000  20.7522  17.8183  24.9964  15.7370
p5    6.2139  11.5262   8.5042  20.7522   0.0000  11.7827   6.4260  22.2764
p6   15.1663  12.5880  14.2484  17.8183  11.7827   0.0000  17.6122  15.6682
p7    7.5770  12.2811  11.5754  24.9964   6.4260  17.6122   0.0000  26.0663
p8   22.2870  22.6390  21.1658  15.7370  22.2764  15.6682  26.0663   0.0000
p9    5.8136  16.5451   7.8223  25.0834   9.0607  20.1520   6.5642  25.0077
p10  17.2017  14.5420  16.0850  19.0948  14.0794   5.5793  19.5309  16.4835
p11   7.0603  16.5630   9.6980  26.5480  10.2167  21.3835   4.6714  27.3081
p12  16.2581  23.7088  15.7029  27.2399  19.7793  28.1617  17.9439  28.8870
p13   6.3722  17.6990   6.7010  24.5123   9.4862  20.1700   9.3517  24.9855
p14  14.0745  21.9183  11.9872  21.1206  17.9957  22.6172  18.2921  22.7133
p15  14.9832  24.3482  10.3056  21.5007  18.7318  20.1195  21.3465  22.7149
p16  18.1176  12.6751  18.0406  17.9540  16.8903  14.0406  20.7551  17.2174
p17  10.9936  20.2660   6.2237  20.5657  14.6649  16.0389  17.1794  20.9961
p18  34.5332  36.9953  33.6223  41.3449  33.8470  31.3864  33.5904  34.0000
p19  12.6716  19.9704   9.8806  18.5681  14.8250  12.4746  18.1241  20.0775
p20  30.1858  30.9444  27.6278  25.9091  30.4577  26.6662  34.2442  25.2812
p21   6.2475  17.8317   5.7158  23.7932  10.7955  19.1318  11.6631  24.3941
p22  30.9273  26.0369  30.8969  22.8263  27.8867  21.2478  31.4345  28.0000
p23   7.7604  16.7896   3.4707  19.8997  11.0558  13.6359  13.5311  20.7580
p24  27.6272  29.9650  26.5447  27.7916  27.2698  21.8259  30.2329  26.0000
p25   6.2655  17.1455   3.7261  21.6024   9.6939  16.7770  12.0825  23.0005
p26  16.2470  22.2862  17.6442  32.5684  19.8554  31.0222  14.2466  30.2062
p27   8.2591  16.1223  11.0449  23.7951  10.9775  20.1791   7.1040  25.0347
p28  25.7794  24.5770  25.9315  25.1566  24.8049  20.3502  25.4408  23.3750
p29  21.2686  30.6336  16.6506  21.8196  24.9184  26.3980  27.5953  24.5071
p30  27.8564  31.3881  28.1974  26.9454  29.4251  31.5653  27.7660  22.0000
p31   8.4445  20.0428   8.8400  25.2543  11.7796  22.2735  11.2841  25.5963
p32  20.8477  24.9628  19.4958  21.9113  23.2218  28.5157  22.5558  23.9540
p33   4.1811  15.4724   5.3988  22.9650   7.4517  17.6455   7.4788  24.1587
p34  10.5702  18.6186  10.4680  22.3727  12.6187  17.7678  13.8847  23.4972
p35  11.9479  21.1362  10.0946  22.4432  15.7675  20.8621  16.6560  21.1811
p36  19.7619  25.9710  17.7912  22.7292  23.0834  26.3396  23.3378  24.8259
p37   8.7837  18.6941   4.7322  22.0918  12.4558  17.3054  14.8613  22.3756
p38  29.1568  27.8386  26.9383  25.7469  27.9106  23.6583  32.4717  20.0000
p39  10.4775  19.8025   5.8536  20.6085  14.0806  15.3879  16.6324  20.8244
p40  12.9221  21.8468   8.6974  20.6299  15.5076  17.0767  18.1091  23.9676
p41  15.5078  22.7035  13.4810  19.4386  16.8859  18.3358  19.6178  22.5810
p42  26.8485  26.6169  26.1244  30.6639  25.2444  25.9151  25.3487  28.1229
p43  15.4061  20.2831  13.6612  18.0469  14.8866  14.4543  18.6365  20.6605
p44  19.8122  26.2115  18.8946  26.2528  22.8800  27.7324  22.0147  25.3875
p45   6.3203  17.3333   7.5390  25.1630   9.5644  20.6714   6.7460  26.2972
p46  22.5864  19.9924  22.8958  28.6777  21.3525  15.6798  23.7511  22.3750
p47   6.0647  17.9712   5.5221  23.3818  10.1765  19.0341  11.5897  24.2200
p48  15.9846  17.5305  15.8816  19.6118  15.3516  15.8813  19.1536  24.6836
p49   7.7450  17.8960   4.1687  21.7399  11.4650  16.6894  13.6627  22.1294
p50  21.0607  18.9604  19.9894  22.6428  18.7128  13.2729  22.7221  24.8039

          p9      p10  ...      p41      p42      p43      p44      p45  \
p1    5.8136  17.2017  ...  15.5078  26.8485  15.4061  19.8122   6.3203
p2   16.5451  14.5420  ...  22.7035  26.6169  20.2831  26.2115  17.3333
p3    7.8223  16.0850  ...  13.4810  26.1244  13.6612  18.8946   7.5390
p4   25.0834  19.0948  ...  19.4386  30.6639  18.0469  26.2528  25.1630
p5    9.0607  14.0794  ...  16.8859  25.2444  14.8866  22.8800   9.5644
p6   20.1520   5.5793  ...  18.3358  25.9151  14.4543  27.7324  20.6714
p7    6.5642  19.5309  ...  19.6178  25.3487  18.6365  22.0147   6.7460
p8   25.0077  16.4835  ...  22.5810  28.1229  20.6605  25.3875  26.2972
p9    0.0000  21.2701  ...  19.4176  27.1961  20.3191  18.3628   2.0832
p10  21.2701   0.0000  ...  17.8350  26.4652  14.7854  28.9408  21.9980
p11   3.5004  22.6338  ...  20.4336  26.6131  21.4057  19.1076   3.5897
p12  13.0641  30.0147  ...  23.2128  27.5550  24.7678  14.0037  12.6940
p13   3.2514  21.4384  ...  19.3271  27.5089  20.3016  16.8711   2.8479
p14  13.4127  24.2273  ...  16.9866  24.3322  18.5212  14.2508  12.9788
p15  14.9836  20.1088  ...  11.2144  30.2357  12.4544  17.5348  14.6459
p16  20.8200  12.6449  ...  21.2409  27.4345  19.5646  21.8242  21.8256
p17  11.3072  16.9481  ...  11.5949  28.9683  12.5622  17.9407  10.6542
p18  34.8782  32.0620  ...  33.6878  28.0521  33.2168  34.3089  34.3840
p19  16.6538  13.3222  ...   9.9430  28.6949   8.9921  22.5079  16.6072
p20  32.1329  24.7626  ...  22.9810  34.3917  23.3423  30.6188  31.2531
p21   5.4885  21.1219  ...  18.1986  27.8784  19.1731  17.2305   5.0122
p22  34.5186  21.4269  ...  29.3438  32.4104  27.7527  43.9857  34.6842
p23   9.1964  14.7638  ...  11.1776  27.7821  12.0048  18.9272   8.9227
p24  30.9549  23.9445  ...  26.9510  28.4104  25.3940  35.2446  30.3342
p25   6.8823  18.3384  ...  15.3028  27.4611  16.2772  18.1883   6.3100
p26  11.0024  32.2725  ...  30.0723  30.5398  31.0017  18.2954  10.4547
p27   7.1313  22.8806  ...  20.0280  27.1718  20.0089  19.2371   6.6677
p28  26.8557  23.1381  ...  30.0766  27.7854  28.2237  30.9321  27.7215
p29  21.2690  25.9071  ...   8.8915  33.3841  12.5930  21.5674  20.9187
p30  26.2777  33.4764  ...  33.1686  32.1229  31.2182  25.6232  26.2631
p31   5.5904  24.0155  ...  21.4662  28.4895  22.4406  15.2891   4.7932
p32  18.6272  28.0918  ...  21.0471  29.9607  23.1267  16.3862  18.4884
p33   3.2731  19.0433  ...  17.4409  26.6900  18.0073  18.3294   3.2544
p34  11.8395  19.6978  ...  17.7301  28.3533  18.2271  19.2887  11.0363
p35  11.6963  19.5717  ...  16.7116  31.6821  17.7118  17.6193  11.6530
p36  18.6694  24.1888  ...  18.1196  32.3440  20.5658  19.5116  18.6924
p37   8.6133  19.0445  ...  15.9322  28.1637  16.9066  16.8152   8.1606
p38  31.5071  21.9975  ...  24.6655  28.2354  24.8675  35.4161  32.1442
p39  11.0262  16.1891  ...  11.1917  28.6834  11.9042  18.2587  10.3496
p40  13.9534  16.3578  ...   9.9571  30.6212  11.0805  20.9909  14.0012
p41  19.4176  17.8350  ...   0.0000  30.5296   4.7483  23.5229  19.9145
p42  27.1961  26.4652  ...  30.5296   0.0000  29.4549  23.4235  26.9430
p43  20.3191  14.7854  ...   4.7483  29.4549   0.0000  25.1410  20.8653
p44  18.3628  28.9408  ...  23.5229  23.4235  25.1410   0.0000  17.5651
p45   2.0832  21.9980  ...  19.9145  26.9430  20.8653  17.5651   0.0000
p46  26.2405  18.3897  ...  26.6401  24.0354  23.5554  32.9054  26.2891
p47   5.3794  20.9393  ...  18.1278  27.6565  19.1022  16.9504   4.8891
p48  17.6654  15.4942  ...  21.2999  30.8214  19.6981  26.2556  17.8501
p49   7.6464  18.6337  ...  15.6001  27.9999  16.4999  17.2262   7.2586
p50  23.7979  12.7440  ...  21.1922  23.1535  19.8365  30.8349  23.9693

         p46      p47      p48      p49      p50
p1   22.5864   6.0647  15.9846   7.7450  21.0607
p2   19.9924  17.9712  17.5305  17.8960  18.9604
p3   22.8958   5.5221  15.8816   4.1687  19.9894
p4   28.6777  23.3818  19.6118  21.7399  22.6428
p5   21.3525  10.1765  15.3516  11.4650  18.7128
p6   15.6798  19.0341  15.8813  16.6894  13.2729
p7   23.7511  11.5897  19.1536  13.6627  22.7221
p8   22.3750  24.2200  24.6836  22.1294  24.8039
p9   26.2405   5.3794  17.6654   7.6464  23.7979
p10  18.3897  20.9393  15.4942  18.6337  12.7440
p11  26.0606   8.0862  19.1410  10.2894  24.2675
p12  32.7003  11.6806  24.8011  13.1854  31.4506
p13  26.9099   2.5543  17.3221   4.8716  24.1152
p14  27.0399   9.9098  19.1998   9.1493  25.2189
p15  27.6566   9.7568  19.4830   7.6838  22.9986
p16  21.3496  21.0768  19.0821  19.7372  15.1125
p17  24.9839   6.5825  17.2808   4.1747  20.8151
p18  27.6250  34.5376  37.5174  34.6557  28.6099
p19  23.6314  14.3445  18.4451  11.7174  18.5425
p20  28.9062  28.3039  27.1699  26.7982  28.3610
p21  25.9874   1.2185  17.2115   2.9512  23.4142
p22  23.6250  34.2084  27.1814  32.8307  17.5776
p23  23.1056   7.0974  16.1116   4.5331  19.2148
p24  16.3750  28.8172  26.2212  27.5946  23.3340
p25  24.8174   2.9968  16.4742   2.5155  22.0552
p26  32.5812  12.1579  25.8630  14.7088  30.9648
p27  23.6376   9.9392  20.8613  11.6826  25.3623
p28  19.7500  28.1426  23.2722  27.5600  28.4397
p29  32.1023  16.9405  25.9697  14.8472  27.5692
p30  34.3750  26.4387  32.3036  26.8548  34.7004
p31  28.2023   3.4572  18.5980   5.9894  26.0101
p32  36.3290  16.8784  26.8275  16.5530  31.0557
p33  25.0542   4.4326  16.3024   6.4903  22.1718
p34  25.4734  10.0838  18.3314   9.9900  23.2411
p35  29.3085   8.5219  19.6438   7.6684  24.4144
p36  35.5420  15.6767  26.2106  14.8307  27.6548
p37  25.3515   3.2936  17.0727   1.3645  22.1053
p38  27.6250  30.0814  27.8846  28.4563  23.4396
p39  24.6495   7.3253  17.1976   4.7636  20.2294
p40  27.5566  11.9742  17.5890   9.6923  19.5538
p41  26.6401  18.1278  21.2999  15.6001  21.1922
p42  24.0354  27.6565  30.8214  27.9999  23.1535
p43  23.5554  19.1022  19.6981  16.4999  19.8365
p44  32.9054  16.9504  26.2556  17.2262  30.8349
p45  26.2891   4.8891  17.8501   7.2586  23.9693
p46   0.0000  25.9106  23.6873  25.0029  18.0022
p47  25.9106   0.0000  16.7444   2.7494  23.1349
p48  23.6873  16.7444   0.0000  16.7695  19.9367
p49  25.0029   2.7494  16.7695   0.0000  21.7223
p50  18.0022  23.1349  19.9367  21.7223   0.0000

[50 rows x 50 columns]

Euclidean, p=2:
         p1      p2      p3      p4      p5      p6      p7      p8      p9  \
p1   0.0000  2.7764  1.1697  4.7726  1.3773  3.0491  1.5305  4.8036  1.2050
p2   2.7764  0.0000  3.3800  4.4545  2.5405  2.7839  2.7539  4.8592  3.4725
p3   1.1697  3.3800  0.0000  4.6713  1.8385  3.1292  2.3997  4.6795  1.6955
p4   4.7726  4.4545  4.6713  0.0000  4.7283  3.8533  5.5091  3.7546  5.5876
p5   1.3773  2.5405  1.8385  4.7283  0.0000  2.7213  1.4334  4.8717  2.0134
p6   3.0491  2.7839  3.1292  3.8533  2.7213  0.0000  3.5629  3.8206  3.9235
p7   1.5305  2.7539  2.3997  5.5091  1.4334  3.5629  0.0000  5.4471  1.4911
p8   4.8036  4.8592  4.6795  3.7546  4.8717  3.8206  5.4471  0.0000  5.3173
p9   1.2050  3.4725  1.6955  5.5876  2.0134  3.9235  1.4911  5.3173  0.0000
p10  3.5643  3.2715  3.4523  4.1080  3.1570  1.4131  4.0958  4.0313  4.3306
p11  1.5055  3.4588  2.1784  5.8640  2.0292  4.1252  1.1108  5.7127  0.7689
p12  3.5843  5.0734  3.4101  6.2067  4.1494  5.1672  4.1538  6.0069  3.4190
p13  1.3488  3.7733  1.4247  5.4754  2.2763  3.9779  2.0382  5.2738  0.7630
p14  3.1140  4.5409  2.6429  4.7707  3.8673  4.4792  4.0145  5.2076  3.2231
p15  3.1023  4.8713  2.2493  4.8391  3.9020  4.1789  4.4308  5.0049  3.4581
p16  3.8513  2.9013  3.9064  4.1135  3.7774  3.4058  4.3396  4.3753  4.3944
p17  2.2607  4.1756  1.4121  4.6248  3.0261  3.5992  3.5447  4.7065  2.6451
p18  6.7281  7.0176  6.6044  8.0033  6.4632  5.6455  6.8354  7.2111  7.2037
p19  2.7398  3.9776  2.1012  4.0655  3.0531  2.5592  3.8496  4.1652  3.4332
p20  6.0044  5.9690  5.6597  5.5353  5.9139  5.0672  6.7730  5.9019  6.6485
p21  1.4769  3.9084  1.2468  5.3470  2.5165  3.9408  2.4190  5.2173  1.2349
p22  6.1637  5.3446  6.2949  5.3554  5.7011  4.5401  6.3551  6.1644  6.8861
p23  1.6243  3.6122  0.8464  4.5309  2.2755  3.1358  2.8316  4.6101  2.1242
p24  5.6883  6.0352  5.6091  6.1226  5.6086  4.6290  6.1652  6.4807  6.4064
p25  1.3863  3.7622  0.9022  4.9756  2.2588  3.5682  2.4515  4.9295  1.4837
p26  3.2080  4.6583  3.6362  6.8988  3.9240  5.5214  3.0732  6.4598  2.4330
p27  1.7845  3.4942  2.4725  5.4497  2.2963  4.0175  1.7927  5.4237  1.8284
p28  5.3583  5.0673  5.6105  6.0138  5.2979  4.3675  5.4048  5.7568  5.7688
p29  4.7684  6.0079  3.9616  5.0362  5.2779  4.9160  6.0717  5.3851  5.3357
p30  5.6610  6.1176  5.8085  5.9889  5.8086  5.6467  5.8750  5.2915  5.8334
p31  1.9646  4.3312  1.8523  5.7589  2.9096  4.4525  2.6729  5.5502  1.4236
p32  4.3894  5.2021  4.1936  5.1520  4.8532  5.3035  5.1207  5.2581  4.4924
p33  0.8692  3.2536  1.2118  5.1584  1.7389  3.4609  1.5660  5.0229  0.6824
p34  2.6364  4.1463  2.6334  5.1514  2.8202  3.7346  3.2793  5.1390  2.9187
p35  2.5758  4.4656  2.1086  5.0041  3.3523  4.1596  3.6931  4.7485  2.6826
p36  4.0204  5.4018  3.6928  5.0872  4.5919  4.9044  4.9836  5.2777  4.2402
p37  1.8331  4.1205  1.1431  5.0802  2.7870  3.8615  3.0017  5.0284  1.8762
p38  5.8973  5.6338  5.6182  5.9496  5.6554  4.8116  6.5392  5.2915  6.5106
p39  2.1723  4.0817  1.3129  4.5880  2.8914  3.4312  3.4565  4.6310  2.6013
p40  3.0030  4.3622  2.2667  4.6432  3.3229  3.5997  4.0206  4.9979  3.3614
p41  3.7555  4.7065  3.0834  4.2491  3.9264  3.5650  4.8717  4.7443  4.4947
p42  5.6549  5.5594  5.5302  6.5579  5.2816  5.0473  5.6471  6.3204  6.0045
p43  3.4276  4.1783  2.8927  3.7764  3.5143  2.8818  4.4940  4.2530  4.2826
p44  4.3008  5.3676  4.1259  5.8573  4.7296  5.1286  4.9623  5.6420  4.4793
p45  1.3083  3.6058  1.6969  5.6524  2.0881  4.0069  1.5929  5.5031  0.5498
p46  4.6562  4.2578  4.8978  5.9725  4.5033  3.7897  4.8646  6.0738  5.4342
p47  1.4426  3.8895  1.1805  5.3080  2.4526  3.9121  2.4076  5.2199  1.2164
p48  3.7450  3.9049  3.8276  4.7299  3.7055  3.3116  4.2552  5.3340  4.3036
p49  1.5909  3.9143  0.9707  4.9418  2.5561  3.6764  2.7725  4.8918  1.6946
p50  4.4009  3.9662  4.3559  5.2133  4.0187  3.3235  4.7616  5.6490  5.0316

        p10  ...     p41     p42     p43     p44     p45     p46     p47  \
p1   3.5643  ...  3.7555  5.6549  3.4276  4.3008  1.3083  4.6562  1.4426
p2   3.2715  ...  4.7065  5.5594  4.1783  5.3676  3.6058  4.2578  3.8895
p3   3.4523  ...  3.0834  5.5302  2.8927  4.1259  1.6969  4.8978  1.1805
p4   4.1080  ...  4.2491  6.5579  3.7764  5.8573  5.6524  5.9725  5.3080
p5   3.1570  ...  3.9264  5.2816  3.5143  4.7296  2.0881  4.5033  2.4526
p6   1.4131  ...  3.5650  5.0473  2.8818  5.1286  4.0069  3.7897  3.9121
p7   4.0958  ...  4.8717  5.6471  4.4940  4.9623  1.5929  4.8646  2.4076
p8   4.0313  ...  4.7443  6.3204  4.2530  5.6420  5.5031  6.0738  5.2199
p9   4.3306  ...  4.4947  6.0045  4.2826  4.4793  0.5498  5.4342  1.2164
p10  0.0000  ...  3.6975  5.0515  3.1627  5.5593  4.3981  4.4947  4.2575
p11  4.5811  ...  4.9781  6.0490  4.7265  4.7633  0.7462  5.4248  1.7235
p12  5.6203  ...  5.1325  6.6756  4.9873  4.4169  3.3054  6.5249  3.0736
p13  4.3274  ...  4.2456  6.0718  4.0869  4.2490  0.6128  5.5993  0.5882
p14  4.7873  ...  3.9192  5.8781  3.8819  3.9752  3.1446  5.9337  2.5254
p15  4.3470  ...  2.4237  6.5918  2.7205  4.5189  3.4465  5.9475  2.4464
p16  3.1674  ...  4.5548  5.6352  4.2164  4.9575  4.4980  5.3598  4.4246
p17  3.8431  ...  2.3799  6.1738  2.4831  4.2545  2.6478  5.4718  1.7165
p18  5.8775  ...  6.8298  6.7945  6.4460  7.7658  7.1723  6.2762  7.1408
p19  2.9652  ...  2.1327  5.7364  1.8105  4.6081  3.4601  4.8285  2.7921
p20  4.7935  ...  4.8713  7.5519  4.6892  6.8840  6.5704  6.7988  6.1014
p21  4.2769  ...  3.9058  6.1280  3.7933  4.2945  1.0996  5.4931  0.3024
p22  4.6348  ...  5.9836  6.8260  5.6150  8.4934  6.9949  5.7785  6.9520
p23  3.4249  ...  2.5040  5.7904  2.4183  4.2509  2.1648  5.0120  1.4608
p24  5.1132  ...  5.6087  6.6510  5.1870  7.3054  6.3325  5.1856  6.1216
p25  3.9223  ...  3.4049  5.9137  3.2683  4.2142  1.4200  5.3008  0.6928
p26  5.8666  ...  6.3575  7.2711  6.1725  5.4831  2.3222  6.8278  2.8016
p27  4.6341  ...  4.8831  6.0798  4.4895  4.8230  1.7783  5.0511  2.2628
p28  4.8676  ...  6.1313  6.1371  5.7144  6.7456  5.9533  5.1751  6.0485
p29  4.9486  ...  1.8776  7.4380  2.5932  5.5851  5.3844  6.6943  4.4691
p30  6.0112  ...  6.7157  7.4798  6.1216  6.4978  5.8843  7.2726  5.8703
p31  4.7813  ...  4.5828  6.4336  4.4544  4.2548  1.1385  5.9863  0.8160
p32  5.3340  ...  4.6834  7.0243  4.7597  5.0584  4.5628  7.2195  4.1344
p33  3.8694  ...  4.0225  5.7398  3.7762  4.2349  0.6602  5.1373  0.9054
p34  4.2266  ...  4.0298  6.1409  3.8566  4.4390  2.8937  5.3610  2.7449
p35  4.2534  ...  3.6438  6.7062  3.7064  4.6190  2.6695  6.1504  1.9804
p36  4.6949  ...  4.0550  7.2544  4.2464  5.2659  4.2551  6.9912  3.6737
p37  4.1365  ...  3.3122  6.1377  3.3034  4.1682  1.8013  5.5887  0.7840
p38  4.4143  ...  5.1946  7.0630  5.0195  7.5224  6.6528  6.5872  6.3612
p39  3.6772  ...  2.2805  6.0502  2.3768  4.2220  2.6241  5.3564  1.7357
p40  3.6245  ...  2.3742  6.1337  2.6048  4.7881  3.4394  5.7107  2.7550
p41  3.6975  ...  0.0000  6.4120  1.1310  5.2013  4.5938  5.4331  3.8976
p42  5.0515  ...  6.4120  0.0000  5.9943  5.9511  5.9934  5.4430  6.0729
p43  3.1627  ...  1.1310  5.9943  0.0000  5.0977  4.3755  4.7999  3.7804
p44  5.5593  ...  5.2013  5.9511  5.0977  0.0000  4.4243  6.7437  4.1902
p45  4.3981  ...  4.5938  5.9934  4.3755  4.4243  0.0000  5.4645  1.0486
p46  4.4947  ...  5.4331  5.4430  4.7999  6.7437  5.4645  0.0000  5.5121
p47  4.2575  ...  3.8976  6.0729  3.7804  4.1902  1.0486  5.5121  0.0000
p48  3.4303  ...  4.7159  6.3066  4.3215  5.6184  4.3327  5.3603  4.2683
p49  4.0114  ...  3.2892  6.0547  3.2242  4.1158  1.6454  5.4285  0.6809
p50  2.9744  ...  4.7024  5.0775  4.3907  6.2843  5.0831  4.8495  5.0385

        p48     p49     p50
p1   3.7450  1.5909  4.4009
p2   3.9049  3.9143  3.9662
p3   3.8276  0.9707  4.3559
p4   4.7299  4.9418  5.2133
p5   3.7055  2.5561  4.0187
p6   3.3116  3.6764  3.3235
p7   4.2552  2.7725  4.7616
p8   5.3340  4.8918  5.6490
p9   4.3036  1.6946  5.0316
p10  3.4303  4.0114  2.9744
p11  4.4516  2.2567  5.1830
p12  5.5178  3.1739  6.2978
p13  4.3166  1.1597  5.1049
p14  4.5288  2.3396  5.5815
p15  4.7167  1.8386  5.2098
p16  4.2963  4.2729  3.6844
p17  4.2239  1.0610  4.7874
p18  7.2753  7.0388  6.0530
p19  4.0437  2.2657  4.2107
p20  5.7942  5.7582  5.9364
p21  4.3411  0.7225  5.0603
p22  5.7224  6.7321  4.1298
p23  3.9168  0.9417  4.3984
p24  5.7565  5.9157  5.3687
p25  4.1216  0.5629  4.8505
p26  5.5763  3.3293  6.3769
p27  4.7524  2.6079  5.4552
p28  5.2075  5.9467  6.1785
p29  5.7155  3.8275  5.8674
p30  6.5607  5.8138  6.8097
p31  4.6814  1.3631  5.5619
p32  5.7727  3.8969  6.3509
p33  4.0022  1.2826  4.6981
p34  4.2232  2.7153  4.9004
p35  4.5443  1.7319  5.2397
p36  5.5730  3.3831  5.6443
p37  4.2892  0.3026  4.9841
p38  6.0463  6.0662  5.4434
p39  4.1479  1.0865  4.6471
p40  4.1822  2.2519  4.4245
p41  4.7159  3.2892  4.7024
p42  6.3066  6.0547  5.0775
p43  4.3215  3.2242  4.3907
p44  5.6184  4.1158  6.2843
p45  4.3327  1.6454  5.0831
p46  5.3603  5.4285  4.8495
p47  4.2683  0.6809  5.0385
p48  0.0000  4.1530  4.8109
p49  4.1530  0.0000  4.8919
p50  4.8109  4.8919  0.0000

[50 rows x 50 columns]

Chebyshev, p=inf:
         p1      p2      p3      p4      p5      p6      p7      p8      p9  \
p1   0.0000  1.1222  0.4577  1.6054  0.5352  0.9720  0.4830  1.8524  0.3993
p2   1.1222  0.0000  1.1087  1.4530  1.0297  1.0296  1.2631  1.6224  1.4208
p3   0.4577  1.1087  0.0000  1.7554  0.6614  1.0992  0.6988  1.7554  0.5748
p4   1.6054  1.4530  1.7554  0.0000  1.6570  1.1195  1.8251  1.3933  1.9039
p5   0.5352  1.0297  0.6614  1.6570  0.0000  1.0406  0.5583  1.6516  0.8182
p6   0.9720  1.0296  1.0992  1.1195  1.0406  0.0000  1.0452  1.1020  1.0992
p7   0.4830  1.2631  0.6988  1.8251  0.5583  1.0452  0.0000  1.8251  0.6231
p8   1.8524  1.6224  1.7554  1.3933  1.6516  1.1020  1.8251  0.0000  1.9257
p9   0.3993  1.4208  0.5748  1.9039  0.8182  1.0992  0.6231  1.9257  0.0000

## 2.

In [15]:
df = pd.read_csv('/content/kddcup.data.corrected', header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,0,tcp,http,SF,215,45076,0,0,0,0,...,0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.0,normal.
1,0,tcp,http,SF,162,4528,0,0,0,0,...,1,1.0,0.0,1.00,0.00,0.0,0.00,0.0,0.0,normal.
2,0,tcp,http,SF,236,1228,0,0,0,0,...,2,1.0,0.0,0.50,0.00,0.0,0.00,0.0,0.0,normal.
3,0,tcp,http,SF,233,2032,0,0,0,0,...,3,1.0,0.0,0.33,0.00,0.0,0.00,0.0,0.0,normal.
4,0,tcp,http,SF,239,486,0,0,0,0,...,4,1.0,0.0,0.25,0.00,0.0,0.00,0.0,0.0,normal.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4898426,0,tcp,http,SF,212,2288,0,0,0,0,...,255,1.0,0.0,0.33,0.05,0.0,0.01,0.0,0.0,normal.
4898427,0,tcp,http,SF,219,236,0,0,0,0,...,255,1.0,0.0,0.25,0.05,0.0,0.01,0.0,0.0,normal.
4898428,0,tcp,http,SF,218,3610,0,0,0,0,...,255,1.0,0.0,0.20,0.05,0.0,0.01,0.0,0.0,normal.
4898429,0,tcp,http,SF,219,1234,0,0,0,0,...,255,1.0,0.0,0.17,0.05,0.0,0.01,0.0,0.0,normal.
4898430,0,tcp,http,SF,219,1098,0,0,0,0,...,255,1.0,0.0,0.14,0.05,0.0,0.01,0.0,0.0,normal.

In [16]:
categorical_columns = df.select_dtypes(include=['object']).columns
print('categorical attributes:', categorical_columns)
categorical_data = df[categorical_columns]
print('categorical data:\n', categorical_data)

categorical attributes: Index([1, 2, 3, 41], dtype='int64')
categorical data:
           1     2   3        41
0        tcp  http  SF  normal.
1        tcp  http  SF  normal.
2        tcp  http  SF  normal.
3        tcp  http  SF  normal.
4        tcp  http  SF  normal.
...      ...   ...  ..      ...
4898426  tcp  http  SF  normal.
4898427  tcp  http  SF  normal.
4898428  tcp  http  SF  normal.
4898429  tcp  http  SF  normal.
4898430  tcp  http  SF  normal.

[4898431 rows x 4 columns]

In [17]:
#Kiem tra gia tri giong nhau
print('so luong dong giong nhau: ', categorical_data.duplicated().sum())

# Loai bo cac dong giong nhau
df1 = categorical_data.drop_duplicates()
print('Du lieu sau khi xoa nhung dong giong nhau: \n', df1)

so luong dong giong nhau:  4897822
Du lieu sau khi xoa nhung dong giong nhau:
           1         2     3                 41
0        tcp      http    SF           normal.
1288     tcp      http    S2           normal.
1484     tcp      http    S1           normal.
2062     tcp      smtp    SF           normal.
2067     udp  domain_u    SF           normal.
...      ...       ...   ...               ...
4574130  tcp       bgp   REJ          neptune.
4575586  tcp    Z39_50   REJ          neptune.
4578870  tcp      smtp    SF          neptune.
4579297  tcp     other  RSTO          neptune.
4810949  tcp    telnet  RSTO  buffer_overflow.

[609 rows x 4 columns]

In [18]:
# Lấy 100 dòng
data = df1.iloc[:100, :].values
n = data.shape[0]
d = data.shape[1]

# Tính tần suất số lần xuất hiện
frequencies = {}
for col in range(d):
    value_counts = pd.Series(data[:, col]).value_counts()
    frequencies[col] = value_counts.to_dict()

def overlap_coefficient(x, y):
    sim = 0
    for i in range(len(x)):
        if x[i] == y[i]:
            sim += 1
    return sim / len(x)

def iof(x, y):
    sim = 0
    for i in range(len(x)):
        freq_x = frequencies[i].get(x[i], 1)
        freq_y = frequencies[i].get(y[i], 1)
        if x[i] == y[i]:
            sim += 1
        else:
            sim += 1 / (1 + np.log(freq_x) * np.log(freq_y))
    return sim / len(x)

# matrix
overlap_sim_matrix = np.zeros((n, n))
iof_sim_matrix = np.zeros((n, n))

for i in range(n):
    for j in range(i + 1, n):
        overlap_sim = overlap_coefficient(data[i], data[j])
        overlap_sim_matrix[i, j] = overlap_sim
        overlap_sim_matrix[j, i] = overlap_sim

        iof_sim = iof(data[i], data[j])
        iof_sim_matrix[i, j] = iof_sim
        iof_sim_matrix[j, i] = iof_sim

def find_nearest_neighbors(sim_matrix, k=5):
    nearest_neighbors = {}
    for i in range(n):
        sim_matrix[i, i] = -1
        indices = np.argsort(sim_matrix[i])[::-1]
        top_k_indices = indices[:k]
        top_k_similarities = sim_matrix[i, top_k_indices]
        nearest_neighbors[i] = list(zip(top_k_indices, top_k_similarities))
    return nearest_neighbors

k = 5
overlap_neighbors = find_nearest_neighbors(overlap_sim_matrix, k)
iof_neighbors = find_nearest_neighbors(iof_sim_matrix, k)

print("Overlap")
for i, neighbors in overlap_neighbors.items():
    print(f"Point {i}:")
    for neighbor, sim in neighbors:
        print(f"  - Point {neighbor}: {sim:.4f}")

print("IOF")
for i, neighbors in iof_neighbors.items():
    print(f"Point {i}:")
    for neighbor, sim in neighbors:
        print(f"  - Point {neighbor}: {sim:.4f}")

print("\nMatrix Overlap")
labels = [f"Point {i}" for i in range(n)]
df_overlap = pd.DataFrame(overlap_sim_matrix, index=labels, columns=labels)
print(df_overlap.iloc[:100, :100].round(4))

print("\nMatrix IOF")
df_iof = pd.DataFrame(iof_sim_matrix, index=labels, columns=labels)
print(df_iof.iloc[:100, :100].round(4))

Overlap
Point 0:
  - Point 75: 0.7500
  - Point 11: 0.7500
  - Point 14: 0.7500
  - Point 2: 0.7500
  - Point 7: 0.7500
Point 1:
  - Point 0: 0.7500
  - Point 2: 0.7500
  - Point 14: 0.7500
  - Point 15: 0.7500
  - Point 24: 0.7500
Point 2:
  - Point 1: 0.7500
  - Point 10: 0.7500
  - Point 15: 0.7500
  - Point 32: 0.7500
  - Point 24: 0.7500
Point 3:
  - Point 96: 0.7500
  - Point 81: 0.7500
  - Point 75: 0.7500
  - Point 11: 0.7500
  - Point 0: 0.7500
Point 4:
  - Point 12: 0.7500
  - Point 75: 0.5000
  - Point 27: 0.5000
  - Point 0: 0.5000
  - Point 11: 0.5000
Point 5:
  - Point 75: 0.7500
  - Point 6: 0.7500
  - Point 0: 0.7500
  - Point 11: 0.7500
  - Point 31: 0.7500
Point 6:
  - Point 75: 0.7500
  - Point 90: 0.7500
  - Point 0: 0.7500
  - Point 11: 0.7500
  - Point 31: 0.7500
Point 7:
  - Point 75: 0.7500
  - Point 11: 0.7500
  - Point 20: 0.7500
  - Point 10: 0.7500
  - Point 6: 0.7500
Point 8:
  - Point 17: 0.7500
  - Point 13: 0.7500
  - Point 75: 0.5000
  - Point 29: 0.5000
  - Point 3: 0.5000
Point 9:
  - Point 25: 0.7500
  - Point 20: 0.7500
  - Point 21: 0.7500
  - Point 7: 0.7500
  - Point 85: 0.5000
Point 10:
  - Point 19: 0.7500
  - Point 18: 0.7500
  - Point 7: 0.7500
  - Point 32: 0.7500
  - Point 2: 0.7500
Point 11:
  - Point 75: 0.7500
  - Point 6: 0.7500
  - Point 5: 0.7500
  - Point 3: 0.7500
  - Point 31: 0.7500
Point 12:
  - Point 4: 0.7500
  - Point 75: 0.5000
  - Point 27: 0.5000
  - Point 0: 0.5000
  - Point 11: 0.5000
Point 13:
  - Point 26: 0.7500
  - Point 23: 0.7500
  - Point 17: 0.7500
  - Point 8: 0.7500
  - Point 3: 0.5000
Point 14:
  - Point 1: 0.7500
  - Point 0: 0.7500
  - Point 2: 0.7500
  - Point 15: 0.7500
  - Point 30: 0.7500
Point 15:
  - Point 1: 0.7500
  - Point 0: 0.7500
  - Point 2: 0.7500
  - Point 14: 0.7500
  - Point 24: 0.7500
Point 16:
  - Point 31: 0.7500
  - Point 99: 0.5000
  - Point 96: 0.5000
  - Point 98: 0.5000
  - Point 83: 0.5000
Point 17:
  - Point 8: 0.7500
  - Point 13: 0.7500
  - Point 75: 0.5000
  - Point 26: 0.5000
  - Point 12: 0.5000
Point 18:
  - Point 96: 0.7500
  - Point 3: 0.7500
  - Point 10: 0.7500
  - Point 32: 0.7500
  - Point 2: 0.7500
Point 19:
  - Point 96: 0.7500
  - Point 79: 0.7500
  - Point 47: 0.7500
  - Point 34: 0.7500
  - Point 7: 0.7500
Point 20:
  - Point 25: 0.7500
  - Point 21: 0.7500
  - Point 7: 0.7500
  - Point 9: 0.7500
  - Point 85: 0.5000
Point 21:
  - Point 25: 0.7500
  - Point 20: 0.7500
  - Point 7: 0.7500
  - Point 9: 0.7500
  - Point 85: 0.5000
Point 22:
  - Point 67: 0.5000
  - Point 66: 0.5000
  - Point 69: 0.5000
  - Point 70: 0.5000
  - Point 79: 0.5000
Point 23:
  - Point 26: 0.7500
  - Point 13: 0.7500
  - Point 8: 0.5000
  - Point 17: 0.5000
  - Point 85: 0.2500
Point 24:
  - Point 67: 0.7500
  - Point 0: 0.7500
  - Point 14: 0.7500
  - Point 2: 0.7500
  - Point 15: 0.7500
Point 25:
  - Point 21: 0.7500
  - Point 33: 0.7500
  - Point 34: 0.7500
  - Point 35: 0.7500
  - Point 7: 0.7500
Point 26:
  - Point 23: 0.7500
  - Point 13: 0.7500
  - Point 8: 0.5000
  - Point 17: 0.5000
  - Point 85: 0.2500
Point 27:
  - Point 4: 0.5000
  - Point 12: 0.5000
  - Point 87: 0.2500
  - Point 90: 0.2500
  - Point 66: 0.2500
Point 28:
  - Point 75: 0.7500
  - Point 6: 0.7500
  - Point 5: 0.7500
  - Point 11: 0.7500
  - Point 31: 0.7500
Point 29:
  - Point 75: 0.7500
  - Point 6: 0.7500
  - Point 5: 0.7500
  - Point 32: 0.7500
  - Point 7: 0.7500
Point 30:
  - Point 29: 0.7500
  - Point 14: 0.7500
  - Point 32: 0.7500
  - Point 96: 0.5000
  - Point 7: 0.5000
Point 31:
  - Point 75: 0.7500
  - Point 6: 0.7500
  - Point 5: 0.7500
  - Point 11: 0.7500
  - Point 7: 0.7500
Point 32:
  - Point 2: 0.7500
  - Point 29: 0.7500
  - Point 18: 0.7500
  - Point 10: 0.7500
  - Point 30: 0.7500
Point 33:
  - Point 35: 0.7500
  - Point 25: 0.7500
  - Point 34: 0.7500
  - Point 79: 0.5000
  - Point 19: 0.5000
Point 34:
  - Point 79: 0.7500
  - Point 47: 0.7500
  - Point 35: 0.7500
  - Point 33: 0.7500
  - Point 25: 0.7500
Point 35:
  - Point 34: 0.7500
  - Point 25: 0.7500
  - Point 33: 0.7500
  - Point 79: 0.5000
  - Point 37: 0.5000
Point 36:
  - Point 71: 0.7500
  - Point 76: 0.7500
  - Point 73: 0.7500
  - Point 63: 0.7500
  - Point 45: 0.7500
Point 37:
  - Point 64: 0.7500
  - Point 72: 0.7500
  - Point 74: 0.7500
  - Point 58: 0.7500
  - Point 46: 0.7500
Point 38:
  - Point 73: 0.7500
  - Point 71: 0.7500
  - Point 66: 0.7500
  - Point 80: 0.7500
  - Point 45: 0.7500
Point 39:
  - Point 72: 0.7500
  - Point 74: 0.7500
  - Point 66: 0.7500
  - Point 64: 0.7500
  - Point 46: 0.7500
Point 40:
  - Point 73: 0.7500
  - Point 71: 0.7500
  - Point 60: 0.7500
  - Point 63: 0.7500
  - Point 45: 0.7500
Point 41:
  - Point 64: 0.7500
  - Point 72: 0.7500
  - Point 74: 0.7500
  - Point 58: 0.7500
  - Point 46: 0.7500
Point 42:
  - Point 73: 0.7500
  - Point 71: 0.7500
  - Point 60: 0.7500
  - Point 63: 0.7500
  - Point 45: 0.7500
Point 43:
  - Point 64: 0.7500
  - Point 72: 0.7500
  - Point 74: 0.7500
  - Point 58: 0.7500
  - Point 46: 0.7500
Point 44:
  - Point 78: 0.7500
  - Point 48: 0.7500
  - Point 59: 0.7500
  - Point 56: 0.7500
  - Point 49: 0.7500
Point 45:
  - Point 73: 0.7500
  - Point 71: 0.7500
  - Point 60: 0.7500
  - Point 63: 0.7500
  - Point 46: 0.7500
Point 46:
  - Point 64: 0.7500
  - Point 72: 0.7500
  - Point 74: 0.7500
  - Point 58: 0.7500
  - Point 45: 0.7500
Point 47:
  - Point 79: 0.7500
  - Point 48: 0.7500
  - Point 59: 0.7500
  - Point 56: 0.7500
  - Point 19: 0.7500
Point 48:
  - Point 77: 0.7500
  - Point 50: 0.7500
  - Point 59: 0.7500
  - Point 56: 0.7500
  - Point 49: 0.7500
Point 49:
  - Point 96: 0.7500
  - Point 97: 0.7500
  - Point 59: 0.7500
  - Point 56: 0.7500
  - Point 48: 0.7500
Point 50:
  - Point 82: 0.7500
  - Point 48: 0.7500
  - Point 59: 0.7500
  - Point 56: 0.7500
  - Point 49: 0.7500
Point 51:
  - Point 68: 0.7500
  - Point 66: 0.7500
  - Point 65: 0.7500
  - Point 62: 0.7500
  - Point 38: 0.7500
Point 52:
  - Point 73: 0.7500
  - Point 71: 0.7500
  - Point 83: 0.7500
  - Point 63: 0.7500
  - Point 45: 0.7500
Point 53:
  - Point 64: 0.7500
  - Point 72: 0.7500
  - Point 74: 0.7500
  - Point 58: 0.7500
  - Point 46: 0.7500
Point 54:
  - Point 73: 0.7500
  - Point 71: 0.7500
  - Point 84: 0.7500
  - Point 63: 0.7500
  - Point 45: 0.7500
Point 55:
  - Point 64: 0.7500
  - Point 72: 0.7500
  - Point 74: 0.7500
  - Point 58: 0.7500
  - Point 46: 0.7500
Point 56:
  - Point 49: 0.7500
  - Point 48: 0.7500
  - Point 50: 0.7500
  - Point 59: 0.7500
  - Point 47: 0.7500
Point 57:
  - Point 73: 0.7500
  - Point 71: 0.7500
  - Point 86: 0.7500
  - Point 63: 0.7500
  - Point 45: 0.7500
Point 58:
  - Point 64: 0.7500
  - Point 72: 0.7500
  - Point 74: 0.7500
  - Point 57: 0.7500
  - Point 46: 0.7500
Point 59:
  - Point 49: 0.7500
  - Point 48: 0.7500
  - Point 50: 0.7500
  - Point 56: 0.7500
  - Point 47: 0.7500
Point 60:
  - Point 73: 0.7500
  - Point 71: 0.7500
  - Point 88: 0.7500
  - Point 63: 0.7500
  - Point 45: 0.7500
Point 61:
  - Point 65: 0.7500
  - Point 68: 0.7500
  - Point 60: 0.7500
  - Point 62: 0.7500
  - Point 51: 0.7500
Point 62:
  - Point 65: 0.7500
  - Point 68: 0.7500
  - Point 51: 0.7500
  - Point 61: 0.7500
  - Point 69: 0.5000
Point 63:
  - Point 73: 0.7500
  - Point 71: 0.7500
  - Point 64: 0.7500
  - Point 89: 0.7500
  - Point 45: 0.7500
Point 64:
  - Point 72: 0.7500
  - Point 74: 0.7500
  - Point 58: 0.7500
  - Point 63: 0.7500
  - Point 46: 0.7500
Point 65:
  - Point 68: 0.7500
  - Point 51: 0.7500
  - Point 61: 0.7500
  - Point 62: 0.7500
  - Point 67: 0.5000
Point 66:
  - Point 70: 0.7500
  - Point 69: 0.7500
  - Point 67: 0.7500
  - Point 51: 0.7500
  - Point 38: 0.7500
Point 67:
  - Point 66: 0.7500
  - Point 68: 0.7500
  - Point 69: 0.7500
  - Point 70: 0.7500
  - Point 24: 0.7500
Point 68:
  - Point 67: 0.7500
  - Point 65: 0.7500
  - Point 61: 0.7500
  - Point 62: 0.7500
  - Point 51: 0.7500
Point 69:
  - Point 70: 0.7500
  - Point 67: 0.7500
  - Point 66: 0.7500
  - Point 65: 0.5000
  - Point 68: 0.5000
Point 70:
  - Point 69: 0.7500
  - Point 67: 0.7500
  - Point 66: 0.7500
  - Point 93: 0.5000
  - Point 65: 0.5000
Point 71:
  - Point 73: 0.7500
  - Point 72: 0.7500
  - Point 60: 0.7500
  - Point 63: 0.7500
  - Point 45: 0.7500
Point 72:
  - Point 64: 0.7500
  - Point 74: 0.7500
  - Point 71: 0.7500
  - Point 58: 0.7500
  - Point 46: 0.7500
Point 73:
  - Point 74: 0.7500
  - Point 71: 0.7500
  - Point 60: 0.7500
  - Point 63: 0.7500
  - Point 45: 0.7500
Point 74:
  - Point 64: 0.7500
  - Point 73: 0.7500
  - Point 72: 0.7500
  - Point 58: 0.7500
  - Point 46: 0.7500
Point 75:
  - Point 95: 0.7500
  - Point 6: 0.7500
  - Point 5: 0.7500
  - Point 11: 0.7500
  - Point 7: 0.7500
Point 76:
  - Point 99: 0.7500
  - Point 98: 0.7500
  - Point 93: 0.7500
  - Point 92: 0.7500
  - Point 83: 0.7500
Point 77:
  - Point 97: 0.7500
  - Point 78: 0.7500
  - Point 79: 0.7500
  - Point 82: 0.7500
  - Point 48: 0.7500
Point 78:
  - Point 97: 0.7500
  - Point 77: 0.7500
  - Point 82: 0.7500
  - Point 95: 0.7500
  - Point 79: 0.7500
Point 79:
  - Point 97: 0.7500
  - Point 77: 0.7500
  - Point 78: 0.7500
  - Point 82: 0.7500
  - Point 47: 0.7500
Point 80:
  - Point 99: 0.7500
  - Point 98: 0.7500
  - Point 93: 0.7500
  - Point 92: 0.7500
  - Point 76: 0.7500
Point 81:
  - Point 97: 0.7500
  - Point 90: 0.7500
  - Point 94: 0.7500
  - Point 95: 0.7500
  - Point 85: 0.7500
Point 82:
  - Point 97: 0.7500
  - Point 78: 0.7500
  - Point 77: 0.7500
  - Point 94: 0.7500
  - Point 79: 0.7500
Point 83:
  - Point 99: 0.7500
  - Point 98: 0.7500
  - Point 93: 0.7500
  - Point 92: 0.7500
  - Point 76: 0.7500
Point 84:
  - Point 99: 0.7500
  - Point 98: 0.7500
  - Point 93: 0.7500
  - Point 92: 0.7500
  - Point 76: 0.7500
Point 85:
  - Point 98: 0.7500
  - Point 90: 0.7500
  - Point 94: 0.7500
  - Point 95: 0.7500
  - Point 81: 0.7500
Point 86:
  - Point 99: 0.7500
  - Point 98: 0.7500
  - Point 93: 0.7500
  - Point 92: 0.7500
  - Point 76: 0.7500
Point 87:
  - Point 99: 0.7500
  - Point 90: 0.7500
  - Point 94: 0.7500
  - Point 95: 0.7500
  - Point 81: 0.7500
Point 88:
  - Point 99: 0.7500
  - Point 98: 0.7500
  - Point 93: 0.7500
  - Point 92: 0.7500
  - Point 76: 0.7500
Point 89:
  - Point 99: 0.7500
  - Point 98: 0.7500
  - Point 93: 0.7500
  - Point 92: 0.7500
  - Point 76: 0.7500
Point 90:
  - Point 87: 0.7500
  - Point 85: 0.7500
  - Point 94: 0.7500
  - Point 95: 0.7500
  - Point 81: 0.7500
Point 91:
  - Point 99: 0.7500
  - Point 98: 0.7500
  - Point 93: 0.7500
  - Point 92: 0.7500
  - Point 76: 0.7500
Point 92:
  - Point 99: 0.7500
  - Point 98: 0.7500
  - Point 88: 0.7500
  - Point 93: 0.7500
  - Point 76: 0.7500
Point 93:
  - Point 99: 0.7500
  - Point 98: 0.7500
  - Point 88: 0.7500
  - Point 92: 0.7500
  - Point 76: 0.7500
Point 94:
  - Point 87: 0.7500
  - Point 85: 0.7500
  - Point 90: 0.7500
  - Point 95: 0.7500
  - Point 82: 0.7500
Point 95:
  - Point 87: 0.7500
  - Point 85: 0.7500
  - Point 90: 0.7500
  - Point 94: 0.7500
  - Point 81: 0.7500
Point 96:
  - Point 97: 0.7500
  - Point 18: 0.7500
  - Point 3: 0.7500
  - Point 49: 0.7500
  - Point 19: 0.7500
Point 97:
  - Point 96: 0.7500
  - Point 78: 0.7500
  - Point 81: 0.7500
  - Point 82: 0.7500
  - Point 77: 0.7500
Point 98:
  - Point 99: 0.7500
  - Point 89: 0.7500
  - Point 93: 0.7500
  - Point 92: 0.7500
  - Point 80: 0.7500
Point 99:
  - Point 98: 0.7500
  - Point 89: 0.7500
  - Point 93: 0.7500
  - Point 92: 0.7500
  - Point 80: 0.7500
IOF
Point 0:
  - Point 28: 1.0000
  - Point 1: 1.0000
  - Point 5: 1.0000
  - Point 15: 1.0000
  - Point 31: 0.8491
Point 1:
  - Point 5: 1.0000
  - Point 2: 1.0000
  - Point 15: 1.0000
  - Point 0: 1.0000
  - Point 14: 1.0000
Point 2:
  - Point 1: 1.0000
  - Point 15: 1.0000
  - Point 14: 0.8491
  - Point 24: 0.8218
  - Point 18: 0.8006
Point 3:
  - Point 28: 1.0000
  - Point 5: 1.0000
  - Point 31: 0.8615
  - Point 11: 0.8342
  - Point 6: 0.8342
Point 4:
  - Point 27: 1.0000
  - Point 12: 1.0000
  - Point 23: 0.8403
  - Point 26: 0.8403
  - Point 17: 0.8403
Point 5:
  - Point 75: 1.0000
  - Point 9: 1.0000
  - Point 11: 1.0000
  - Point 15: 1.0000
  - Point 7: 1.0000
Point 6:
  - Point 28: 1.0000
  - Point 5: 1.0000
  - Point 31: 0.8919
  - Point 11: 0.8633
  - Point 75: 0.8491
Point 7:
  - Point 5: 1.0000
  - Point 20: 1.0000
  - Point 21: 1.0000
  - Point 9: 1.0000
  - Point 28: 1.0000
Point 8:
  - Point 26: 1.0000
  - Point 23: 1.0000
  - Point 17: 1.0000
  - Point 13: 1.0000
  - Point 27: 0.8403
Point 9:
  - Point 7: 1.0000
  - Point 5: 1.0000
  - Point 21: 1.0000
  - Point 20: 1.0000
  - Point 28: 1.0000
Point 10:
  - Point 22: 0.8218
  - Point 19: 0.8026
  - Point 18: 0.7947
  - Point 32: 0.7947
  - Point 21: 0.7945
Point 11:
  - Point 28: 1.0000
  - Point 5: 1.0000
  - Point 31: 0.8919
  - Point 6: 0.8633
  - Point 75: 0.8491
Point 12:
  - Point 27: 1.0000
  - Point 4: 1.0000
  - Point 23: 0.8403
  - Point 26: 0.8403
  - Point 17: 0.8403
Point 13:
  - Point 26: 1.0000
  - Point 23: 1.0000
  - Point 17: 1.0000
  - Point 8: 1.0000
  - Point 12: 0.8403
Point 14:
  - Point 1: 1.0000
  - Point 15: 1.0000
  - Point 2: 0.8491
  - Point 24: 0.8342
  - Point 0: 0.8036
Point 15:
  - Point 5: 1.0000
  - Point 0: 1.0000
  - Point 14: 1.0000
  - Point 2: 1.0000
  - Point 1: 1.0000
Point 16:
  - Point 1: 0.8491
  - Point 15: 0.8491
  - Point 31: 0.7713
  - Point 28: 0.7713
  - Point 5: 0.7713
Point 17:
  - Point 26: 1.0000
  - Point 23: 1.0000
  - Point 8: 1.0000
  - Point 13: 1.0000
  - Point 27: 0.8403
Point 18:
  - Point 32: 0.8094
  - Point 96: 0.8026
  - Point 15: 0.8006
  - Point 2: 0.8006
  - Point 1: 0.8006
Point 19:
  - Point 10: 0.8026
  - Point 34: 0.7949
  - Point 96: 0.7947
  - Point 22: 0.7927
  - Point 15: 0.7877
Point 20:
  - Point 7: 1.0000
  - Point 5: 1.0000
  - Point 21: 1.0000
  - Point 9: 1.0000
  - Point 28: 1.0000
Point 21:
  - Point 7: 1.0000
  - Point 5: 1.0000
  - Point 20: 1.0000
  - Point 9: 1.0000
  - Point 28: 1.0000
Point 22:
  - Point 69: 1.0000
  - Point 70: 0.8400
  - Point 33: 0.8342
  - Point 10: 0.8218
  - Point 35: 0.7959
Point 23:
  - Point 26: 1.0000
  - Point 17: 1.0000
  - Point 8: 1.0000
  - Point 13: 1.0000
  - Point 4: 0.8403
Point 24:
  - Point 1: 1.0000
  - Point 15: 1.0000
  - Point 14: 0.8342
  - Point 2: 0.8218
  - Point 22: 0.7877
Point 25:
  - Point 9: 1.0000
  - Point 21: 1.0000
  - Point 20: 1.0000
  - Point 33: 0.8036
  - Point 7: 0.7949
Point 26:
  - Point 17: 1.0000
  - Point 23: 1.0000
  - Point 8: 1.0000
  - Point 13: 1.0000
  - Point 4: 0.8403
Point 27:
  - Point 4: 1.0000
  - Point 12: 1.0000
  - Point 17: 0.8403
  - Point 8: 0.8403
  - Point 5: 0.7919
Point 28:
  - Point 75: 1.0000
  - Point 9: 1.0000
  - Point 11: 1.0000
  - Point 1: 1.0000
  - Point 7: 1.0000
Point 29:
  - Point 28: 1.0000
  - Point 5: 1.0000
  - Point 31: 0.8615
  - Point 11: 0.8342
  - Point 6: 0.8342
Point 30:
  - Point 32: 0.8491
  - Point 28: 0.8036
  - Point 5: 0.8036
  - Point 29: 0.8036
  - Point 14: 0.8006
Point 31:
  - Point 28: 1.0000
  - Point 5: 1.0000
  - Point 11: 0.8919
  - Point 6: 0.8919
  - Point 75: 0.8775
Point 32:
  - Point 30: 0.8491
  - Point 18: 0.8094
  - Point 1: 0.8006
  - Point 15: 0.8006
  - Point 2: 0.8006
Point 33:
  - Point 22: 0.8342
  - Point 35: 0.8170
  - Point 34: 0.8129
  - Point 25: 0.8036
  - Point 21: 0.8036
Point 34:
  - Point 33: 0.8129
  - Point 79: 0.7968
  - Point 19: 0.7949
  - Point 22: 0.7927
  - Point 47: 0.7911
Point 35:
  - Point 33: 0.8170
  - Point 22: 0.7959
  - Point 34: 0.7823
  - Point 25: 0.7769
  - Point 21: 0.7769
Point 36:
  - Point 73: 0.8615
  - Point 71: 0.8615
  - Point 40: 0.8615
  - Point 42: 0.8615
  - Point 45: 0.8615
Point 37:
  - Point 72: 0.8615
  - Point 74: 0.8615
  - Point 41: 0.8615
  - Point 43: 0.8615
  - Point 46: 0.8615
Point 38:
  - Point 73: 0.8615
  - Point 71: 0.8615
  - Point 40: 0.8615
  - Point 42: 0.8615
  - Point 45: 0.8615
Point 39:
  - Point 72: 0.8615
  - Point 74: 0.8615
  - Point 41: 0.8615
  - Point 43: 0.8615
  - Point 46: 0.8615
Point 40:
  - Point 73: 0.9189
  - Point 71: 0.9189
  - Point 45: 0.9189
  - Point 42: 0.9189
  - Point 60: 0.8919
Point 41:
  - Point 72: 0.9189
  - Point 74: 0.9189
  - Point 46: 0.9189
  - Point 43: 0.9189
  - Point 55: 0.8919
Point 42:
  - Point 73: 0.9189
  - Point 71: 0.9189
  - Point 45: 0.9189
  - Point 40: 0.9189
  - Point 60: 0.8919
Point 43:
  - Point 72: 0.9189
  - Point 74: 0.9189
  - Point 46: 0.9189
  - Point 41: 0.9189
  - Point 55: 0.8919
Point 44:
  - Point 48: 0.8491
  - Point 50: 0.8491
  - Point 59: 0.8491
  - Point 56: 0.8491
  - Point 49: 0.8218
Point 45:
  - Point 73: 0.9189
  - Point 71: 0.9189
  - Point 40: 0.9189
  - Point 42: 0.9189
  - Point 60: 0.8919
Point 46:
  - Point 72: 0.9189
  - Point 74: 0.9189
  - Point 41: 0.9189
  - Point 43: 0.9189
  - Point 55: 0.8919
Point 47:
  - Point 48: 0.8155
  - Point 50: 0.8155
  - Point 59: 0.8155
  - Point 56: 0.8155
  - Point 44: 0.8049
Point 48:
  - Point 59: 0.8633
  - Point 50: 0.8633
  - Point 56: 0.8633
  - Point 44: 0.8491
  - Point 49: 0.8342
Point 49:
  - Point 48: 0.8342
  - Point 50: 0.8342
  - Point 59: 0.8342
  - Point 56: 0.8342
  - Point 44: 0.8218
Point 50:
  - Point 59: 0.8633
  - Point 48: 0.8633
  - Point 56: 0.8633
  - Point 44: 0.8491
  - Point 49: 0.8342
Point 51:
  - Point 65: 0.8615
  - Point 62: 0.8342
  - Point 61: 0.8342
  - Point 69: 0.8144
  - Point 66: 0.8144
Point 52:
  - Point 73: 0.8919
  - Point 71: 0.8919
  - Point 40: 0.8919
  - Point 42: 0.8919
  - Point 45: 0.8919
Point 53:
  - Point 72: 0.8919
  - Point 74: 0.8919
  - Point 41: 0.8919
  - Point 43: 0.8919
  - Point 46: 0.8919
Point 54:
  - Point 73: 0.8919
  - Point 71: 0.8919
  - Point 40: 0.8919
  - Point 42: 0.8919
  - Point 45: 0.8919
Point 55:
  - Point 72: 0.8919
  - Point 74: 0.8919
  - Point 41: 0.8919
  - Point 43: 0.8919
  - Point 46: 0.8919
Point 56:
  - Point 48: 0.8633
  - Point 50: 0.8633
  - Point 59: 0.8633
  - Point 44: 0.8491
  - Point 49: 0.8342
Point 57:
  - Point 73: 0.8919
  - Point 71: 0.8919
  - Point 40: 0.8919
  - Point 42: 0.8919
  - Point 45: 0.8919
Point 58:
  - Point 72: 0.8919
  - Point 74: 0.8919
  - Point 41: 0.8919
  - Point 43: 0.8919
  - Point 46: 0.8919
Point 59:
  - Point 48: 0.8633
  - Point 50: 0.8633
  - Point 56: 0.8633
  - Point 44: 0.8491
  - Point 49: 0.8342
Point 60:
  - Point 73: 0.8919
  - Point 71: 0.8919
  - Point 40: 0.8919
  - Point 42: 0.8919
  - Point 45: 0.8919
Point 61:
  - Point 65: 0.8919
  - Point 62: 0.8633
  - Point 51: 0.8342
  - Point 68: 0.8232
  - Point 69: 0.8144
Point 62:
  - Point 65: 0.8919
  - Point 61: 0.8633
  - Point 51: 0.8342
  - Point 68: 0.8232
  - Point 69: 0.8144
Point 63:
  - Point 73: 0.8919
  - Point 71: 0.8919
  - Point 40: 0.8919
  - Point 42: 0.8919
  - Point 45: 0.8919
Point 64:
  - Point 72: 0.8919
  - Point 74: 0.8919
  - Point 41: 0.8919
  - Point 43: 0.8919
  - Point 46: 0.8919
Point 65:
  - Point 61: 0.8919
  - Point 62: 0.8919
  - Point 51: 0.8615
  - Point 68: 0.8491
  - Point 69: 0.8144
Point 66:
  - Point 69: 1.0000
  - Point 70: 0.8615
  - Point 51: 0.8144
  - Point 67: 0.8006
  - Point 39: 0.7959
Point 67:
  - Point 69: 1.0000
  - Point 70: 0.8491
  - Point 68: 0.8144
  - Point 66: 0.8006
  - Point 22: 0.7877
Point 68:
  - Point 65: 0.8491
  - Point 62: 0.8232
  - Point 61: 0.8232
  - Point 69: 0.8144
  - Point 67: 0.8144
Point 69:
  - Point 70: 1.0000
  - Point 67: 1.0000
  - Point 66: 1.0000
  - Point 22: 1.0000
  - Point 65: 0.8144
Point 70:
  - Point 69: 1.0000
  - Point 66: 0.8615
  - Point 67: 0.8491
  - Point 22: 0.8400
  - Point 65: 0.7332
Point 71:
  - Point 73: 0.9189
  - Point 45: 0.9189
  - Point 40: 0.9189
  - Point 42: 0.9189
  - Point 54: 0.8919
Point 72:
  - Point 74: 0.9189
  - Point 46: 0.9189
  - Point 41: 0.9189
  - Point 43: 0.9189
  - Point 58: 0.8919
Point 73:
  - Point 71: 0.9189
  - Point 45: 0.9189
  - Point 40: 0.9189
  - Point 42: 0.9189
  - Point 54: 0.8919
Point 74:
  - Point 72: 0.9189
  - Point 46: 0.9189
  - Point 41: 0.9189
  - Point 43: 0.9189